# Site title and description
title: "Elca"
title_short: ""
description: "Your site description"
keywords: "your,keywords,here"
author: "Qxel"
remote_theme: LittleCeo/elca

plugins:
  - jekyll-remote-theme
# Logo (optional)
logo: "https://Littleceo.github.io/logos/elca.png" # Path to your logo

# NEW Navigation configuration - Updated for the new navigation system
navigation:
  Home: 
    url: /index.md
  Adnan:
    - Assignment: /adnan/assignment
    - Seminar: /adnan/seminar
  Jaseel:
    - Assignment: /jaseel/assignment
    - "Athulya Assignment": /jaseel/athulya_assignment
    - "Navas Assignment": /jaseel/navas_assignment
  "My Notes":
    - "Aseena Assignment": /my/aseena_assignment
    - "Aseena Seminar": /my/aseena_seminar
    - Assignment: /my/assignment
    - "Athulya Assignment": /my/athulya_assignment
    - Seminar: /my/seminar
    - "Suji Assignment": /my/suji_assignment
    - "Suji Seminar": /my/suji_seminar
  Noushique:
    - Assignment: /noushique/assignment
    - Seminar: /noushique/seminar
  BCA:
    - "Sinan Assignment": /sinan/assignment
  Calicut:
    - BEPOLI:
      - "Operating Project": /calicut/bepoli/op
    - NIKKOLA:
      - "Nokil project": /calicut/nikkola/noki
